### ISSUE TITLE
dbt model for OP-RF4 metrics for all projects in oss-directory over all time (time series)

### ISSUE THREAD

**Issue by ryscheng** [opensource-observer/oso#1721]
### What is it?

We should have dashboards for all funded metrics, the first of which are RF4 metrics. We should maintain these models into the future so that we can demonstrate different types of counterfactuals.
- Pre / post RF 4 funding - did it move the needle?
- Pre-post  RF X funding - did other rounds move the needle without explicitly funding it? (what are the other factors)
- Funded and non-funded projects - does it move the needle for either set in the long run?

The types of things we want to know are:
- Are the ecosystem changes sticky? Which metrics, when funded have that effect?
- Does it require perpetual continuous funding? Or are large periodic injections enough?

I'm sure there are many more questions we want to ask

**Comment by ryscheng** [comment]
This is probably the right time to introduce a `metrics_id`, we want to know exactly what definition was funded at what time

**Comment by ccerv1** [comment]
## derived events

```
name: fulltime_developers
namespace: oso
source: OSO
event_sources:
  - GITHUB
event_types:
  - COMMIT_CODE
to_types:
  - artifact
  - project
  - collection
from_types:
  - id_type: artifact
     id_registry: trusted
aggregation_functions:
  - mean
window_intervals:
  - unit: day
    value: 30
    missing_dates: fill_with_zero
sampling_interval: daily
```
