### ISSUE TITLE
feat: `usergroup` schema

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#1998]
### Describe the feature you'd like to request

A `usergroup` is to users what a `collection` is to projects.
A user should be able to specify a YAML file that enumerates an array of `user_source_id`s as part of a `usergroup`. 
For example:

```yaml
version: x
name: kariba_data_collective
display_name: Active Members of Kariba Data Collective
git_users:
  - ccerv1
  - ryscheng
  - ravenac95
farcaster_users:
  - 529
  - 63755
  - 297654
eoas:
  - 0x...
  - 0x...
```

The collection should then resolve the distinct artifacts owned by members of the `usergroup`.

Perhaps the `usergroup_namespace` could be the sub-directory where the `usergroup` is defined ?

### Describe the solution you'd like

We need both static `usergroups` and dynamic ones. A dynamic `usergroup` would be something like a bot filter or OpenRank-generated list.

I could imagine a new directory we maintain the looks something like this:

```
usergroups/
│
├── oso/
│   ├── models/
│   │   ├── oso_bot_filter.sql
│   │   ├── oso_power_addresses.sql
│   │
│   └── static/
│       ├── kariba_data_collective.yaml
│       └── data_challenge_winners.yaml
│
└── superchain/
    ├── models/
    │   ├── superchain_bot_filter.sql
    │   ├── superchain_power_addresses.sql
    │   └── superchain_trusted_users.sql
    │
    └── static/
        ├── op_airdrop_1.yaml
        ├── op_airdrop_2.yaml
        ├── op_badgeholders.yaml
        └── op_coredevs.yaml
```

We would then need some dbt macros to process these into a `usergroups` table.

### Describe alternatives you've considered

We could continue to hardcode usergroups into our dbt models and upload static datasets to BigQuery.
