### ISSUE TITLE
bug: OSSD doesn't support open collective fields

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2314]
### What is it?

We'd like to create open collective artifacts, eg,

```
version: 7
name: eslint
display_name: ESLint
websites:
  - url: https://eslint.org
social:
  twitter:
    - url: https://x.com/geteslint
github:
  - url: https://github.com/eslint
npm:
  - url: https://www.npmjs.com/package/eslint
  - url: https://www.npmjs.com/package/@eslint/js
  - url: https://www.npmjs.com/package/@eslint/eslintrc
  - url: https://www.npmjs.com/package/@eslint/config-array
  - url: https://www.npmjs.com/package/@eslint/object-schema
  - url: https://www.npmjs.com/package/@eslint/compat
  - url: https://www.npmjs.com/package/@eslint/plugin-kit
  - url: https://www.npmjs.com/package/@eslint/config-inspector
  - url: https://www.npmjs.com/package/@eslint/core
  - url: https://www.npmjs.com/package/@eslint/json
  - url: https://www.npmjs.com/package/@eslint/migrate-config
open_collective:
  - url: https://opencollective.com/eslint
```

However, we haven't done a schema migration to handle these. As result, the pipeline is currently failing.

Action:
- Move the open collective artifacts to websites for now
- Fix the build
- Rematerialize

cc @Jabolol
