### ISSUE TITLE
Integrate @evmexplorer/blockscout sdk

### ISSUE THREAD

**Issue by Pfed-prog** [opensource-observer/oso#2688]
### Describe the feature you'd like to request

A list of potential features:

- native token balances and token balances.
- contract creator address.
- if contract of a project has a token such as erc20, obtain more data about the token such as circulating market cap, total supply, number of holders and market price.

### Describe the solution you'd like

Integrate https://www.npmjs.com/package/@evmexplorer/blockscout to fetch address information and subsequently token balances:

```js
export { AddressInfoBlockscout } from "@evmexplorer/blockscout";
export { fetchAddressInfo } from "@evmexplorer/blockscout";
const addressData: AddressInfoBlockscout = await fetchAddressInfo(
    '0x940181a94A35A4569E4529A3CDfB74e38FD98631'
  );
```

## Example Output
```yaml
{
  block_number_balance_updated_at: 24455600,
  coin_balance: '0',
  creation_transaction_hash: '0x5727b7b346eb94d6f139e10e7ac922158dacd84f5d2844c01cf815b29d9ba58c',
  creator_address_hash: '0xe83f922C34A1962e9aE9F52B59e18239764f2818',
  ens_domain_name: null,
  exchange_rate: '3355.72',
  has_beacon_chain_withdrawals: false,
  has_decompiled_code: false,
  has_logs: true,
  has_token_transfers: true,
  has_tokens: true,
  has_validated_blocks: false,
  hash: '0x940181a94A35A4569E4529A3CDfB74e38FD98631',
  implementations: [],
  is_contract: true,
  is_scam: false,
  is_verified: true,
  metadata: null,
  name: 'Aero',
  private_tags: [],
  proxy_type: null,
  public_tags: [],
  token: {
    address: '0x940181a94A35A4569E4529A3CDfB74e38FD98631',
    circulating_market_cap: '956823083.4110918',
    decimals: '18',
    exchange_rate: '1.32',
    holders: '256658',
    icon_url: 'https://assets.coingecko.com/coins/images/31745/small/token.png?1696530564',
    name: 'Aerodrome',
    symbol: 'AERO',
    total_supply: '1430061314928507549104557113',
    type: 'ERC-20',
    volume_24h: '67878838.84853496'
  },
  watchlist_address_id: null,
  watchlist_names: []
}
```
## Fetch Tokens

```js
export type { AddressTokens } from "@evmexplorer/blockscout";
export { fetchTokensAddress } from "@evmexplorer/blockscout";

const tokensData: AddressTokens = await fetchTokensAddress(
  '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
);
```

## Output

```yaml
[
{
  token: {
    address: '0x28561B8A2360F463011c16b6Cc0B0cbEF8dbBcad',
    circulating_market_cap: '75858317.61202328',
    decimals: '9',
    exchange_rate: '0.00017784',
    holders: '14334',
    icon_url: 'https://assets.coingecko.com/coins/images/50348/small/1000000612.jpg?1727248974',
    name: 'MOO DENG',
    symbol: 'MOODENG',
    total_supply: '420690000000000000000',
    type: 'ERC-20',
    volume_24h: '10219755.637613483'
  },
  token_id: null,
  token_instance: null,
  value: '30000105889157756560'
},
....
]
```

### Describe alternatives you've considered

I considered querying the token history and aggregating the data. It could be further integrated into @evmexplorer/blockscout sdk.
