### ISSUE TITLE
Create model to run and union our weighted dependency graphs

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#2809]
### What is it?

First, we need some intermediate model or generic way of constructing the event graph.
Then we should be able to call our new openrank.py and run at least two different weighting algorithms.
Finally, we need to union the results into a new model, eg, `int_weighted_dependency_graph`

- onchain_builder_project_id
- dev_tooling_project_id
- edge_type
- edge_weight
- weighting_algorithm
- created_at

Probably best to have this in a single SQLMesh Python model that can be executed on demand.

**Comment by ccerv1** [comment]
FYI, I am working on this primarily in the [private repo](https://github.com/ethereum-optimism/Retro-Funding) Optimims set up for algorithm testing.

For example, here is a set of weighting parameters for one of the devtooling algos that I've been using for testing. 

```
onchain_importance:
  alpha: 0.4   # weight for total transactions
  beta: 0.4    # weight for total active users
  gamma: 0.2   # weight for total gas fee contribution

package_dependency:
  base_dependency_weight: 1.0
  dependency_source_weights:
    CARGO: 2.0
    NPM: 1.0
    GITHUB: 0.5

developer_connections:
  event_weights:
    COMMIT_CODE: 3
    FORKED: 1
    STARRED: 1
    ISSUE_CLOSED: 1
    ISSUE_COMMENT: 2
    ISSUE_OPENED: 2
    ISSUE_REOPENED: 1
    PULL_REQUEST_CLOSED: 1
    PULL_REQUEST_MERGED: 2
    PULL_REQUEST_OPENED: 2
    PULL_REQUEST_REOPENED: 1
    PULL_REQUEST_REVIEW_COMMENT: 2
    
  default_reputation: 0.2

  fanout_exponent: 1.0

  time_decay:
    half_life_days: 180   # Each 180 days older an event is, it loses half its weight

pagerank:
  damping_factor: 0.85
  max_iterations: 100
  convergence_threshold: 1.0e-7
```
