### ISSUE TITLE
Bedrock defillama data is missing from before '2025-03-24'

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#3413]
## Checking current coverage

Query the following to Trino:

```
  select * from oso.stg__defillama_tvl_events
  where slug = 'bedrock-unibtc'
  order by time
```

<img width="829" alt="Image" src="https://github.com/user-attachments/assets/60dc10d4-fdac-401e-bdf1-59abd6a7ff91" />

It should go back much longer than one day.

## Confirming source data

The source data is there. You can check in BigQuery:

```
select slug, chain_tvls from `defillama.tvl`
where slug = 'bedrock-unibtc'
```

## Tried restating

Just ran a [restate job](https://dagster.opensource.observer/runs/dee8537e-f8c1-4916-afcf-3d0f7ef7b23a) on the staging model. Configs were:

```
ops:
  sqlmesh_project_3:
    config:
      restate_selected: true
      start: 2022-01-01
      end: 2025-03-25
```

Job ran successfully but returned the same data.
