### ISSUE TITLE
Reuven / David 2024-01-31 Call Notes 

### ISSUE THREAD

**Issue by davidgasquez** [opensource-observer/oso#814]
### What is it?

Hey! Dumping here some of what we discussed @ravenac95!

### Incremental dbt models

Right now, even though the [GitHub events materialization is incremental](https://github.com/opensource-observer/oso/blob/main/dbt/models/github_events.sql), you'll need
to add the `is_incremental()` macro logic to make dbt understand what are the new events/rows. You might need to do other things (defining unique keys and [updating the incremental strategy](https://discourse.getdbt.com/t/google-cloud-bigquery-ddl-costs-runtime-partitions-to-replace-vs-dbt-max-partition-vs-copy-partitions/9838)).

The final model could look like this:

```sql
{{
    config(
        materialized="incremental")
        partition_by={
            "field": "created_at",
            "data_type": "timestamp",
            "granularity": "day"
        },
        unique_key="id",
        on_schema_change="append_new_columns",
        incremental_strategy="insert_overwrite"
    )
}}

with base as (
    select * from {{ source("gh_events") }}
    where repo in (select repo from {{ source("oso_repos") }}) -- Should be cheaper for BQ!

    {% if is_incremental() %}
    and _TABLE_SUFFIX > format_timestamp("%m%d", timestamp_sub(_dbt_max_partition, interval 1 day))
    {% endif %}
)
```

You might need to add a [`dbt-utils` snippet to deduplicate](https://github.com/dbt-labs/dbt-utils)!

```
{{ dbt_utils.deduplicate(
    relation='base',
    partition_by='id',
    order_by='created_at desc'
   )
}}
```

### Development environments in dbt

To avoid affecting production and also saving some :money_with_wings:, you can setup dbt to use `dbt_[user]` schemas when you run things in your laptop or CI. These schemas can at the same time limit the data they scan or do everything via `views` so they're fast!

You'll need to version the `profiles.yaml` file and add a couple of env vars. Something like this:

```yaml
default:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: oso
      schema: "dbt_{{ env_var('DBT_USER') }}"
      threads: 32
    production:
      type: bigquery
      method: oauth
      project: oso
      dataset: production
      threads: 32
  target: "{{ env_var('DBT_TARGET') }}"
```

Oh! dbt will look for the profiles.yaml` file at `DBT_PROFILES_DIR`.

Now you can start adding [conditional logic to the models based on the target](https://docs.getdbt.com/reference/dbt-jinja-functions/target#examples)!

---

Awesome work so far! Been great to follow along! :smile:
