### ISSUE TITLE
Users of an OP Impact Calculator apps should be able to audit the query for any OSO impact metric

### ISSUE THREAD

**Issue by ccerv1** [opensource-observer/oso#978]

**Comment by ccerv1** [comment]
We should auto-generate the fields required by the Voting UI (see [here](https://github.com/karibalabs/private-internal/blob/main/misc/rf4_metrics.yaml)) using the same flow as #959 

Example:

```yaml
- id: rf4_gas_fees
  name: Gas Fees
  external_link: https://github.com/opensource-observer/oso/blob/main/warehouse/dbt/models/marts/superchain/metrics/rf4_gas_fees.sql
  short_description: Sum of a project's total contribution to gas fees across the Superchain
  long_description: |
    Gas fees are the primary recurring revenue source for the Superchain and a key indicator of aggregate blockspace demand. A project’s gas fee contribution is influenced by its total volume of contract interactions, the computational complexity of those interactions, and the state of the underlying gas market at the time of those transactions. In the long run, gas fees are what will power Retro Funding and enable it to continue in perpetuity. All members of the Superchain have committed at least 15% of their gross profit from gas fees to Retro Funding. Supporting projects that generate revenue in the form of gas fees helps power the economic engine of the Superchain.

```
